services:
  weather:
    image: weather
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - weather_app/.env
    ports:
      - 8000:8000
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: hubxp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres